apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomdep
spec:
  selector:
    matchLabels:
      app: tomdep
  replicas: 1
  template:
    metadata:
      labels:
        app: tomdep
    spec:
      containers:
        - name: tomcatcontainer
          image: venkatapavan524/vproapp
          ports:
            - containerPort: 8080