apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomdep
spec:
  selector:
    matchLabels:
      app: tomdep
  replicas: 1
  template:
    metadata:
      labels:
        app: tomdep
    spec:
      containers:
        - name: tomcatcontainer
          image: venkatapavan524/vproapp
          ports:
            - containerPort: 8080
      initContainers:
        - name: initdb
          image: busybox
          command: ["sh","-c","until nslookup vprodb; do echo waiting for mydb; sleep 2; done;"]
        - name: initmem
          image: busybox
          command: ["sh","-c","until nslookup vprocache01; do echo waiting for mymem; sleep 2; done;"]